### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by arturek1666** [GamerKing195/Up2Date#1]
Not sure really how to fix that

:44:51] [pool-17-thread-3/ERROR]: [U2D] ============== BEGIN ERROR ==============
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] PLUGIN VERSION: Up2Date V1.2.1
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] PLUGIN MESSAGE: Error occurred while pinging Spigot!
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] MESSAGE: null
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] STACKTRACE: 
[23:44:51] [pool-17-thread-3/WARN]: java.lang.NullPointerException
[23:44:51] [pool-17-thread-3/WARN]: 	at be.maximvdw.spigotsite.resource.SpigotResourceManager.getResourceById(SourceFile:50)
[23:44:51] [pool-17-thread-3/WARN]: 	at com.gamerking195.dev.up2date.command.SetupCommand.parsePriorities(SetupCommand.java:396)
[23:44:51] [pool-17-thread-3/WARN]: 	at com.gamerking195.dev.up2date.command.SetupCommand.lambda$parsePlugins$0(SetupCommand.java:240)
[23:44:51] [pool-17-thread-3/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:44:51] [pool-17-thread-3/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:44:51] [pool-17-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:44:51] [pool-17-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:44:51] [pool-17-thread-3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-3/ERROR]: [U2D] ============== END ERROR ==============
[23:44:51] [Server thread/INFO]: xomgx[/xx.xx.xx.xx.xx:40158] logged in with entity id 7033 at ([spawn]-1.4022458464587453, 75.0, 1.3736467056617943)
[23:44:51] [Craft Scheduler Thread - 34/INFO]: [AuthMe] xomgx logged in!
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] A severe error has occurred with the Up2Date plugin.
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/GamerKing195/Up2Date/issues.
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] ============== BEGIN ERROR ==============
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] PLUGIN VERSION: Up2Date V1.2.1
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] PLUGIN MESSAGE: Error occurred while pinging Spigot!
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] MESSAGE: null
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] STACKTRACE: 
[23:44:51] [pool-17-thread-2/WARN]: java.lang.NullPointerException
[23:44:51] [pool-17-thread-2/WARN]: 	at be.maximvdw.spigotsite.resource.SpigotResourceManager.getResourceById(SourceFile:50)
[23:44:51] [pool-17-thread-2/WARN]: 	at com.gamerking195.dev.up2date.command.SetupCommand.parsePriorities(SetupCommand.java:396)
[23:44:51] [pool-17-thread-2/WARN]: 	at com.gamerking195.dev.up2date.command.SetupCommand.lambda$parsePlugins$0(SetupCommand.java:240)
[23:44:51] [pool-17-thread-2/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:44:51] [pool-17-thread-2/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:44:51] [pool-17-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:44:51] [pool-17-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:44:51] [pool-17-thread-2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] 
[23:44:51] [pool-17-thread-2/ERROR]: [U2D] ============== END ERROR ==============

**Comment by GamerKing195** [comment]
Hey there, could you please provide more context, what were you doing and what did this break?

**Comment by arturek1666** [comment]
I was just doing the setup :), Could not connect my spigot account so i decided to skip it and continue however it stuck on 97% and nothing is happening

**Comment by GamerKing195** [comment]
Did you re-try the setup, it looks like u2d tried to ping spigot for a resource that didn't exist (for the second part of the error) which could be because it's checking for a premium resource without an account but it's dubious. I've experienced the connection failed exception somewhat seldom throughout testing and it usually fixed itself if you re-try assuming your server has an internet connection.

**Comment by arturek1666** [comment]
I mean players play on the server so there is internet xD. Ok will try to do setup again

**Comment by GamerKing195** [comment]
Hey there, did this fix the problem or do you still require more support?

**Comment by arturek1666** [comment]
I just give up xD
