### ISSUE TITLE
Error on trying to login to spigot

### ISSUE THREAD

**Issue by arturek1666** [GamerKing195/Up2Date#8]
[10:39:23] [Server thread/INFO]: [AutoUpdaterAPI] U2D Authenticating account... [ATTEMPTING DECRYPT]
[10:39:23] [Server thread/INFO]: [AutoUpdaterAPI] U2D Authenticating account... [ATTEMPTING AUTHENTICATION]
[10:39:24] [Server thread/INFO]: [AutoUpdaterAPI] U2D Authenticating account... [RE-ATTEMPTING AUTHENTICATION]
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: java.lang.IllegalArgumentException: Empty key
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at be.maximvdw.spigotsite.utils.TOTP.hmac_sha1(SourceFile:213)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at be.maximvdw.spigotsite.utils.TOTP.generateTOTP(SourceFile:184)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at be.maximvdw.spigotsite.utils.TOTP.generateTOTP(SourceFile:130)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at be.maximvdw.spigotsite.utils.TOTP.generateTOTP(SourceFile:73)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at be.maximvdw.spigotsite.user.SpigotUserManager.totpVerification(SourceFile:145)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SourceFile:110)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SourceFile:67)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at com.gamerking195.dev.autoupdaterapi.PremiumUpdater$2.run(SourceFile:311)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:39:25] [Craft Scheduler Thread - 1772/WARN]: [AutoUpdaterAPI] Plugin AutoUpdaterAPI v2.2.1 generated an exception while executing task 168030
java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330) ~[?:1.8.0_144]
	at java.lang.Class.isAnonymousClass(Class.java:1411) ~[?:1.8.0_144]
	at co.aikar.timings.MinecraftTimings.getPluginTaskTimings(MinecraftTimings.java:63) ~[craftbukkit.jar:git-Paper-1298]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.<init>(CraftTask.java:41) ~[craftbukkit.jar:git-Paper-1298]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:139) ~[craftbukkit.jar:git-Paper-1298]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:113) ~[craftbukkit.jar:git-Paper-1298]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:96) ~[craftbukkit.jar:git-Paper-1298]
	at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:43) ~[craftbukkit.jar:git-Paper-1298]
	at com.gamerking195.dev.autoupdaterapi.util.b.b(SourceFile:77) ~[AutoUpdaterAPI.jar:?]
	at com.gamerking195.dev.autoupdaterapi.PremiumUpdater$2.run(SourceFile:315) ~[AutoUpdaterAPI.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[craftbukkit.jar:git-Paper-1298]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit.jar:git-Paper-1298]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [craftbukkit.jar:git-Paper-1298]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[10:39:25] [Server thread/INFO]: [AutoUpdaterAPI] U2D Authenticating account... [INVALID CACHED CREDENTIALS]

I give up before but after update i try again and it's happening again don't really understand why it can't connect to spigot and it gives error I do use paperspigot, so may be that's the reason any idea what might cause this issue?

**Comment by arturek1666** [comment]
Or may be becouse I use bungeecord?

**Comment by magemaniac33** [comment]
Seems like your SpigotMC credentials aren't working: "U2D Authenticating account... [INVALID CACHED CREDENTIALS]"

Try deleting the "/plugins/.creds/" folder. That'll remove any cached login, then restart your server and set the plugin back up again.

**Comment by arturek1666** [comment]
I try but still nothing xD

**Comment by arturek1666** [comment]
I know I type the info corectly but don't understand why i don't connects

**Comment by magemaniac33** [comment]
I just re-read the plugin page feeling stupid.

Try doing: /up2date login

Also if you have 2 Factor Auth... Well it's not the key in your app, you'd have to remove 2FA in your account and set it up again. It'll give you a 2FA code, that's what you use instead.

**Comment by arturek1666** [comment]
I didn't had but i was thinking I need it for plugin to work haha so i done it but still nothing haha. OK will try /up2date login

**Comment by arturek1666** [comment]
Nope nothing is fixing this xD.

**Comment by magemaniac33** [comment]
I'm not too sure. I'm held up on another bug that goes to load all the plugins, but is stuck on the 2nd to last one so the plugin kinda doesn't do anything after that xD

Hopefully within a few weeks the dev will smash out these issues and the plugin will be solid.

**Comment by GamerKing195** [comment]
Hello, thankyou for the bug report, I'll start looking into this as soon as I can. Thankyou to @magemaniac33 for providing accurate and helpful information so that now I know it is a bug within the code.

**Comment by GamerKing195** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Login failing for certain users](https://trello.com/c/Ci8Cpp2B/61-fix-login-failing-for-certain-users)

**Comment by arturek1666** [comment]
One more thing I just notice that in plugins /SpigotUpdates i have settup it to false before is this what might cause issues?

**Comment by GamerKing195** [comment]
I'm not surewhat the SpigotUpdates folder is, all files for Up2Date are either in plugins/u2d or just plugins for installing plugins.

**Comment by arturek1666** [comment]
ok never mind then may be that's was from plugin i deleted before never mind xD

**Comment by GamerKing195** [comment]
Hey there, after investigating this I can't seem to re-create it. Every time I enter my valid two-factor key it completes the login successfully and every time I don't I get that error in console and the GUI re-opens prompting me for credentials.

Please make sure you're getting the correct key, here's a segment of the tutorial video that shows you where to get it. https://youtu.be/gSnFSRUTqGU?t=12m43s

**Comment by arturek1666** [comment]
Nice than I will have no acces  to my account NOPE I will not do that
